### ISSUE TITLE
Frontend - persist data across pages, and only fetch once

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/Helios#26]
Could do this by fetching all data in the App component when it mounts, then pass to children as needed. You can also use localStorage or other methods I think.

**Comment by JackBlake-zkq** [comment]
Essentially, we should be able to make one call to aggregateOutputData form `fetchData.js`, and have access to all of the data from any page.

**Comment by JackBlake-zkq** [comment]
See [this PR](https://github.com/DSSD-Madison/Helios/pull/28) for details about the aggregateOutputData function

**Comment by MaxMaeder** [comment]
I don't know if we need this, the only time this would be needed is for the admin interface and it might be better just to fetch every time so the data is the most recent/accurate.

**Comment by JackBlake-zkq** [comment]
True, I'll close this for now and if we ever end up with more pages that rely on the data we can re-open
