### ISSUE TITLE
Dashboard - Highlights banner at top of page

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/Helios#51]
As shown in [Mockup](https://www.figma.com/file/jsbaHg87LXpSpa7evCFSRj/Helios-Solar-Array-Analytics?node-id=0-1)

Sum output of all arrays

Use average cost of electricity (hardcoded or from some API) in Madison to display $ saved to date

Use average energy/barrel of oil (hardcoded or from some API) to display Oil Barrels avoided to date

**Comment by MaxMaeder** [comment]
What do you mean by this?

**Comment by JackBlake-zkq** [comment]
Just added description
